### ISSUE TITLE
No layout manager attached!!!

### ISSUE THREAD

**Issue by javierpe** [truizlop/SectionedRecyclerView#1]
Hi, I have a problem to visualize data when I run your example 'AgendaSimpleSectionAdapter', I get this error: 
                          E/RecyclerView﹕ No layout manager attached; skipping layout

**Comment by truizlop** [comment]
You just have to add a LayoutManager as you regularly do with any Adapter you create for a RecyclerView.

``` java
recyclerView.setLayoutManager(new LinearLayoutManager(context));
```
