### ISSUE TITLE
Is there a way to add extra itemTypes

### ISSUE THREAD

**Issue by Qoderapps** [truizlop/SectionedRecyclerView#19]
I see that you are using itemTypes for the footers and headers. I'd like to have a section using other viewHolder type. I haven't digged enough to be sure that another type is possible.

`public int getItemViewType(int position);`

Is there a way to get section index inside this method?

**Comment by truizlop** [comment]
Of course, it is possible. Override method [getSectionItemViewType(section, position)](https://github.com/truizlop/SectionedRecyclerView/blob/master/library/src/main/java/com/truizlop/sectionedrecyclerview/SectionedRecyclerViewAdapter.java#L172) and make sure you provide different view type identifiers than the used for headers and footers.

**Comment by Qoderapps** [comment]
Thanx :) I expected something like this but didn's see it. Great library btw.

**Comment by truizlop** [comment]
Thanks for your feedback!
