### ISSUE TITLE
Does it work with RecyclerView.SortedList?

### ISSUE THREAD

**Issue by subediaayush** [truizlop/SectionedRecyclerView#20]
I was having some issues with displaying the list items where all the headers had same title.
![rec](https://cloud.githubusercontent.com/assets/6436847/22209707/900013b0-e1af-11e6-92ca-597e18e32ff0.png)
Adapter was returning correct title while calling `getSectionHeaderTitle` from 'onBindItemViewHolder'

**Comment by truizlop** [comment]
I cannot help you unless you provide more info

**Comment by subediaayush** [comment]
Nevermind, the problem occured when a section had 0 items. It seems you have to check for empty sections and remove it from the section count.
Cool library though.
