### ISSUE TITLE
Customize Header

### ISSUE THREAD

**Issue by samuel2629** [truizlop/SectionedRecyclerView#25]
Hi,
How can i customize font, text size, text color... in headers?
Thank you! Great Work!

**Comment by truizlop** [comment]
You can always provide your own view for header and footer by extending `SectionedRecyclerViewAdapter` and overriding the appropriate methods, as stated in the documentation. Besides, you can extend `SimpleSectionedAdapter` and override method `getLayourResource` ([see here](https://github.com/truizlop/SectionedRecyclerView/blob/5d7f29df6b65a3de7d3244fe812da1694c5ba12f/library/src/main/java/com/truizlop/sectionedrecyclerview/SimpleSectionedAdapter.java#L66)) to provide a layout for the header that contains a `TextView` with id = `@+id/title_text`. There you can customize the appearance of your header.
